BoVoyageProjetFinal/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BoVoyageProjetFinal.Data;
using BoVoyageProjetFinal.Models;
using BoVoyageProjetFinal.Utils;

namespace BoVoyageProjetFinal.Controllers
{
    public class ClientsController : BaseController
    {
        // GET: /Clients
        public ActionResult Index()
        {
            int? id = null;
            if (Session["CLIENT"] != null)
            {
                id = ((Client)Session["CLIENT"]).ID;
            }
            Client client = db.Clients.Find(id);
            return View(client);
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.CivilityID = new SelectList(db.Civilities, "ID", "Label");
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Mail,Password,ConfirmedPassword,LastName,FirstName,Address,Telephone,Birthdate,CivilityID")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                client.Password = client.Password.HashMD5();
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.CivilityID = new SelectList(db.Civilities, "ID", "Label", client.CivilityID);
            return View(client);
        }

        // GET: Clients/Edit
        public ActionResult Edit()
        {
            int? id = null;
            if (Session["CLIENT"] != null)
            {
                id = ((Client)Session["CLIENT"]).ID;
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.CivilityID = new SelectList(db.Civilities, "ID", "Label", client.CivilityID);
            return View(client);
        }

        // POST: Clients/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Mail,LastName,FirstName,Address,Telephone,Birthdate,CivilityID")] Client client)
        {
            ModelState.Remove("Mail");

            if (ModelState.IsValid)
            {
                client.Password = client.Password.HashMD5();
                db.Entry(client).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CivilityID = new SelectList(db.Civilities, "ID", "Label", client.CivilityID);
            return View();
        }

        // GET: Clients/Delete/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Clients/ChangePassword/
        public ActionResult ChangePassword(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View();
        }

        // POST: BackOffice/SalesmenBO/ChangePassword/
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ClientPasswordViewModel clientPasswordViewModel)
        {
            Client client = Session["CLIENT"] as Client;

            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                client.Password = clientPasswordViewModel.Password.HashMD5();
                db.SaveChanges();

                DisplayMessage("Votre mot de passe a été correctement modifié !!!", MessageType.SUCCESS);

                return RedirectToAction("Index", "HomeClient");
            }
            DisplayMessage("Il y a malheureusement eu un souci :-(", MessageType.ERROR);
            return RedirectToAction("Index", "HomeClient");
        }
    }
}

BoVoyageProjetFinal/Controllers/SharedController.cs
using BoVoyageProjetFinal.Data;
using BoVoyageProjetFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoVoyageProjetFinal.Controllers
{
    public class SharedController : BaseController
    {
        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFiveTravelsDepartureDate()
        {
            var travels = db.Travels.Include("Destination")
                .Include("TravelAgency")
                .OrderBy(x => x.DepartureDate)
                .Take(5);

            return View("_TopFiveTravelsDepartureDate", travels);
        }

        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFiveAllInclusivePrice()
        {
            var travels = db.Travels.Include("Destination")
                .Include("TravelAgency")
                .OrderBy(x => x.AllInclusivePrice)
                .Take(5);

            return View("_TopFiveTravelsDepartureDate", travels);
        }

        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFiveTravelsCountry()
        {
            var destination = db.Travels.Include("Destination")
                .GroupBy(x => x.Destination.Country)
                .OrderByDescending(x => x.Count())
                .Take(5);

            return View("_TopFiveTravelsCountry", destination);
        }
    }
}

BoVoyageProjetFinal/Controllers/TravelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BoVoyageProjetFinal.Models;
using BoVoyageProjetFinal.Data;

namespace BoVoyageProjetFinal.Controllers
{
    public class TravelsController : BaseController
    {
        // GET: Travels
        public ActionResult Index(TravelViewModel model)
        {
            IEnumerable<Travel> liste = db.Travels.Include(x => x.Destination).Include(x => x.TravelAgency);

            if (model.DepartureDateMax != null)
                liste = liste.Where(x => x.DepartureDate <= model.DepartureDateMax);

            if (model.DepartureDateMin != null)
                liste = liste.Where(x => x.DepartureDate >= model.DepartureDateMin);

            if (model.ReturnDateMax != null)
                liste = liste.Where(x => x.ReturnDate <= model.ReturnDateMax);

            if (model.ReturnDateMin != null)
                liste = liste.Where(x => x.ReturnDate >= model.ReturnDateMin);

            if (model.AllInclusivePriceMax != null)
                liste = liste.Where(x => x.AllInclusivePrice <= model.AllInclusivePriceMax);

            if (model.AllInclusivePriceMin != null)
                liste = liste.Where(x => x.AllInclusivePrice >= model.AllInclusivePriceMin);

            if (!string.IsNullOrWhiteSpace(model.Continent))
                liste = db.Travels.Include(x => x.Destination).Include(x => x.TravelAgency).Where(x => x.Destination.Continent.Contains(model.Continent));

            if (!string.IsNullOrWhiteSpace(model.Country))
                liste = db.Travels.Include(x => x.Destination).Include(x => x.TravelAgency).Where(x => x.Destination.Country.Contains(model.Country));

            if (!string.IsNullOrWhiteSpace(model.Region))
                liste = db.Travels.Include(x => x.Destination).Include(x => x.TravelAgency).Where(x => x.Destination.Region.Contains(model.Region));

            model.Travels = liste.ToList();
            return View(model);
        }


        // GET: Travels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Travel travel = db.Travels.Find(id);
            Travel travel = db.Travels.Include(x => x.Destination).Include(t => t.TravelAgency).Include(x => x.Files).SingleOrDefault(x => x.ID == id);

            if (travel == null)
            {
                return HttpNotFound();
            }
            return View(travel);

        }
    }
}

BoVoyageProjetFinal/Views/Shared/_DisplayMessage.cshtml
@{
    Layout = null;
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-@TempData["MessageType"].ToString()">
        @TempData["Message"].ToString()
    </div>
}

BoVoyageProjetFinal/Views/Shared/_Layout.cshtml
@{
    var client = Session["CLIENT"] as BoVoyageProjetFinal.Models.Client;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BoVoyage | @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 2px;">
            @*<img src="~/images/LOGO.png" height="200" width="200" align="middle" />*@
            <a class="navbar-brand" href="~/"><i class="fa fa-plane"></i>Accueil</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href=" @Url.Action("About","Home") ">A propos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" @Url.Action("Index","Travels") ">Voyages</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" @Url.Action("Create","ContactMessages") ">Nous contacter</a>
                    </li>

                    @*
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "Dashboard", new { area = "BackOffice" })">Back Office<span class="sr-only">(current)</span></a>
            </li>
                    *@
                </ul>

                @if (client == null)
                {

                    <span class="navbar-text">
                        <a href="@Url.Action("Create", "Clients")" class="btn btn-info btn-sm">Créer un compte</a>
                    </span>
                    <span> </span>
                    <span class="navbar-text">
                        <a href="@Url.Action("Login", "AuthenticationClient")" class="btn btn-info btn-sm"><i class="fa fa-sign-in"></i> Se connecter</a>
                    </span>
                }
                else
                {
                    <span class="navbar-text">
                        Bonjour @client.FirstName @client.LastName ! <a href="@Url.Action("Index", "HomeClient")" class="btn btn-info btn-sm">Mon compte</a>
                    </span>
                }

            </div>
        </nav>
        @RenderBody()
        <hr />

        <footer class="bg-info text-white">
            &copy; 2018  BoVoyage
            @*@Html.Partial("_TopFive", *@
            @*@@Html.Action("TopFive", "Shared")*@
        </footer>

    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @*<script src="~/Scripts/holder.min.js"></script>*@

    @RenderSection("SectionScripts", false)
</body>
</html>

BoVoyageProjetFinal/Views/Shared/_LayoutClient.cshtml
@{
    Layout = null;
    var client = Session["CLIENT"] as BoVoyageProjetFinal.Models.Client;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Accueil Client | @ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
</head>

<body>
    <<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 2px;">
        <a class="navbar-brand" href="~/">Accueil</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("About","Home") ">A propos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Edit","Clients")">Mon profil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("Index","TravelsClient") ">Voyages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" @Url.Action("Index","ReservationDossiers") ">Mes réservations</a>
                </li>
            </ul>

            <span class="navbar-text">
                Bonjour @client.FirstName @client.LastName ! <a href="@Url.Action("Logout", "AuthenticationClient")" class="btn btn-danger btn-sm"><i class="fa fa-sign-out"></i>Se deconnecter</a>
            </span>
        </div>
    </nav>
    @Html.Partial("_DisplayMessage")
    @RenderBody()
    <hr />

    <footer class="bg-info text-white">
        &copy; 2018  BoVoyage
        @*@Html.Partial("_TopFive", *@
        @*@@Html.Action("TopFive", "Shared")*@
    </footer>

</div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("SectionScripts", false)
</body>
</html>

BoVoyageProjetFinal/Views/Shared/_LayoutForm.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; <!-- Utilise le layout principal car besoin du menu et des scripts principaux-->
}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                @RenderSection("SectionTitle", true) <!--true: Obligation de mettre un titre; titre de la vue qui a appelé mon layout-->
            </div>
            <div class="card-body">
                @RenderBody() <!-- Body de la vue qui m'a appelé Le body comprend tous ce qui n'est pas dans une section de ma vue-->
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
@section SectionScripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("SectionScripts", false) <!-- Rajout des scripts de la vue qui a appelé le Layout, ces scripts supplémentaires ne sont pas obligatooire dans ma vue (false)-->
}

BoVoyageProjetFinal/Views/Shared/_LayoutFormClient.cshtml
@{
    Layout = "~/Views/Shared/_LayoutClient.cshtml"; <!-- Utilise le layout principal car besoin du menu et des scripts principaux-->
}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                @RenderSection("SectionTitle", true) <!--true: Obligation de mettre un titre; titre de la vue qui a appelé mon layout-->
            </div>
            <div class="card-body">
                @RenderBody() <!-- Body de la vue qui m'a appelé Le body comprend tous ce qui n'est pas dans une section de ma vue-->
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
@section SectionScripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("SectionScripts", false) <!-- Rajout des scripts de la vue qui a appelé le Layout, ces scripts supplémentaires ne sont pas obligatooire dans ma vue (false)-->
}

BoVoyageProjetFinal/Views/Shared/_TopFiveTravelsCountry.cshtml
@model IEnumerable<IGrouping<String, BoVoyageProjetFinal.Models.Travel>>
@{
    Layout = null;
}

<table class="table table-hover">
    @foreach (var item in Model)
    {
        <tr>
            <th colspan="4">
                @item.Key
            </th>
        </tr>

        <tr class="table-secondary">
            <th>
                Date de départ
            </th>
            <th>
                Date de retour
            </th>
            <th>
                Prix tout compris
            </th>
            <th></th>
        </tr>


        foreach (var travel in item)
        {
        <tr>
            <td>
                @travel.DepartureDate
            </td>
            <td>
                @travel.ReturnDate
            </td>
            <td>
                @travel.AllInclusivePrice
            </td>
            <td>
                <a href="@Url.Action("Details", "Travels", new { id = travel.ID })" data-toggle="tooltip" data-placement="top" title="Details"><i class="fa fa-search"></i></a>
            </td>
        </tr>
        }
    }
</table>

BoVoyageProjetFinal/Views/Shared/_TopFiveTravelsDepartureDate.cshtml
@model IEnumerable<BoVoyageProjetFinal.Models.Travel>
@{
    Layout = null;
}

<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Destination.Continent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllInclusivePrice)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Destination.Continent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination.Region)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AllInclusivePrice)
        </td>
        <td>
            <a href="@Url.Action("Details", "Travels", new { id = item.ID })" data-toggle="tooltip" data-placement="top" title="Details"><i class="fa fa-search"></i></a>
        </td>
    </tr>
    }
</table>

BoVoyageProjetFinal/Views/Shared/_TopFiveTravelsPrice.cshtml
@model IEnumerable<BoVoyageProjetFinal.Models.Travel>
@{
    Layout = null;
}

<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Destination.Continent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AllInclusivePrice)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Destination.Continent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AllInclusivePrice)
            </td>
        </tr>
    }
</table>